### ISSUE TITLE
send altlog to a tty

### ISSUE THREAD

**Issue by bamarni** [jedisct1/pure-ftpd#40]
Hi,

When running pureftp in the foreground (in my case inside a docker container) it might be useful to send altlogs to stdout. I couldn't manage to do it though, I've tried with both `/dev/stdout` and `/proc/1/fd/1` (1 being the pid of the pureftp server process inside the container).

After looking at the source code [here](https://github.com/jedisct1/pure-ftpd/blob/2c68e0cc5f4e0566270b532c58a8189cd8911280/src/altlog.c#L35-41), it seems like it's because stdout is not seekable?

Is this something you're willing to support?

Thanks

**Comment by jedisct1** [comment]
Should be fixed in d7658b07a455ea6f3d278237df6ba6f153c6d39f

Thanks!

**Comment by bamarni** [comment]
Sorry for the wrong pointer with my assumption, but apparently that part of the code isn't the issue, according to http://linux.die.net/man/2/lseek :

> On Linux, using lseek() on a terminal device returns ESPIPE.

I've just tested against master with verbose logging and got this :

    Jul 31 18:59:22 ac694f3305bc pure-ftpd: (?@192.168.99.1) [INFO] New connection from 192.168.99.1
    Jul 31 18:59:22 ac694f3305bc pure-ftpd: (?@192.168.99.1) [ERROR] altlog /dev/stdout: Too many levels of symbolic links
    Jul 31 18:59:22 ac694f3305bc pure-ftpd: (?@192.168.99.1) [DEBUG] Command [auth] [TLS]

This happens because of the `O_NOFOLLOW` flag when trying to get the file descriptor, I've just opened a PR with a patch (#41), tested locally and worked fine :)

**Comment by jedisct1** [comment]
Does it work if you replace `/dev/stdout` with `$(readlink -f /dev/stdout)`?

**Comment by bamarni** [comment]
Still not, then I think it tries with stdout from the former subshell :

    Jul 31 20:55:26 ac694f3305bc pure-ftpd: (?@192.168.99.1) [ERROR] altlog /proc/17/fd/pipe:[92428]: No such file or directory

I also tried to force the pid (which is 1 in my case) : `$(readlink -f /proc/1/fd/1)`. It didn't work either but in that case no error in the log, not sure why.

**Comment by 0815fox** [comment]
Are there any updates on this? I cannot get pure-ftpd to log anything neither to a log file nor to stdout.

**Comment by bamarni** [comment]
@0815fox : this issue was only about stdout, this should already work fine with a file.
